In [20]:
#Take your data
#Pick a random model
#Calculate the error
#Minimize the error, and obtain a better model
print("\nJ MANASA\n")


#Sigmoid activation function  : σ(x)=1/1+e−x

#Output (prediction) formula : ˆy =σ(w1x1+w2x2+b)

#Error function Error(y,ˆy) = −ylog(ˆy)−(1−y)log(1−ˆy)
#y^ ​	 =σ(Wx+b)

#The function that updates the weights  :  wi⟶ wi+α(y−ˆy)xi
#                                          b⟶  b+α(y− ˆy )


J MANASA



In [21]:
import numpy as np
import torch

torch.manual_seed(7)
inputs = torch.randn((1,5), requires_grad = True)
weights = torch.randn_like(inputs)
bias = torch.randn((1,1))
y = torch.randn((5,1))

print("input values : ",inputs)
print("weights : ",weights)
print("bias : ",bias)
print("output value : ",y)

input values :  tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]], requires_grad=True)
weights :  tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
bias :  tensor([[0.3177]])
output value :  tensor([[0.1328],
        [0.1373],
        [0.2405],
        [1.3955],
        [1.3470]])


In [22]:
def sigmoid(inputs):
    return 1 / (1 + torch.exp(-inputs))
#print(sigmoid(inputs))

y1 = sigmoid(torch.sum(inputs * weights.view(5,1)) + bias)

print(y1)

tensor([[0.0448]], grad_fn=<MulBackward0>)


In [23]:
def softmax(inputs):
    return torch.exp(inputs) / torch.sum(torch.exp(inputs), dim = 1).view(1, -1)
print(softmax(inputs))

propabilities = softmax(y1)
print(propabilities.shape)

print(propabilities.sum(dim = 1))

tensor([[0.0758, 0.1927, 0.2263, 0.0288, 0.4763]], grad_fn=<DivBackward0>)
torch.Size([1, 1])
tensor([1.], grad_fn=<SumBackward1>)


In [24]:
#order to calculate the derivative of this error with respect to the weights,
#∂w j​	 ∂​	  y^

y1 = sigmoid(torch.sum(inputs * weights.view(5,1)) + bias)
xi = y1.backward()
print(inputs.grad)

tensor([[-0.0668, -0.0668, -0.0668, -0.0668, -0.0668]])
